apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "service.name" . }}-analysis-template
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}
    app: {{ include "service.name" . }}
    app.kubernetes.io/version: "1.0.0"
spec:
  metrics:
  - name: {{ include "service.name" . }}-prometheus-metric
    interval: 10s
    successCondition: len(result) == 0 || result[0] >= 0.95
    failureLimit: 2
    provider:
      prometheus:
        address: https://internal:7ZEPDjzOAYEzRhJDVZcICUCcFfRIthOFn0qFmzQG%2FMM72UQHMo6YsZ2cjcTkmn6dzyW8w4gv0TTxohTU2expaGkUZJ7sxvYKvMNXFPDI5VryoO%2BpnR9aX1Q9MOwRdbkfER1auIV2Hgkfa9rKcZlsuzAvWjj9Ffm1MCNAWSOhqtxKitNyR7ZTnVREsVeHuSw%2FlxD%2B06rpzBq8vxewWB8AyaUJYKzMyTzN7j0Dhcb34dqZamfkwco%2FQ3x%2BOoNlmsKstLVeSALqM8AXYq6Vds3M2ypSAn%2BE9UhmoxOwPD%2BHnQJ7LjnpdiV99GjO7JIuQFCbT8W6yKHJbvyNGCgAjhyr@prometheus.istio-system.svc.cluster.local:9090
        query: |
                    sum(irate( istio_requests_total{reporter="source",destination_service_name=~"dstrategies-back",response_code!~"5.*"}[30s] )) / sum(irate( istio_requests_total{reporter="source",destination_service_name=~"dstrategies-back"}[30s] ))
